Add CarbonComponents sample app
IBM/qradar-sample-apps pull request #36
Opened 2021-08-03 15:33 UTC by erin-hughes

This PR adds a new sample application that demonstrates how to use Carbon components in an app generated by v2 of the QRadar App SDK.

Instructions for running locally and deploying are included in the readme. A full tutorial for how to achieve a project of the same structure from scratch is also included.

2021-08-17 16:32 UTC, jthomperoo requested changes
Just a couple things I noticed when testing this out before merging, all super minor otherwise, looks great :)

2021-08-17 16:32 UTC, jthomperoo commented on CarbonComponents/README.md
> +. store/scripts/clean_and_run.sh
Think this might be a typo, I think the script is called `store/scripts/clean_and_run.sh`.

2021-08-17 16:32 UTC, jthomperoo commented on CarbonComponents/app/static/qjslib/qappfw.min.js
> +this.qappfw=function(t){var e={};function r(n){if(e[n])return e[n].exports;var o=e[n]={i:n,l:!1,exports:{}};return t[n].call(o.exports,o,o.exports,r),o.l=!0,o.exports}return r.m=t,r.c=e,r.d=function(
I don't think or the favicon in the static directory is used - maybe could remove these?

2021-08-17 17:16 UTC, erin-hughes commented on CarbonComponents/README.md
> +. store/scripts/clean_and_run.sh
Might be being silly but I don’t see the typo here… If you mean the `.` at the beginning of the line, that's the [bash dot command](https://www.shell-tips.com/bash/source-dot-command/), it's needed to actually run the script. The full command should be `. store/scripts/clean_and_run.sh`.

2021-08-17 17:16 UTC, erin-hughes commented on CarbonComponents/app/static/qjslib/qappfw.min.js
> +this.qappfw=function(t){var e={};function r(n){if(e[n])return e[n].exports;var o=e[n]={i:n,l:!1,exports:{}};return t[n].call(o.exports,o,o.exports,r),o.l=!0,o.exports}return r.m=t,r.c=e,r.d=function(
This minified file was autogenerated when I ran `qapp create` - I assumed it was important/needed for the apps generated by the App SDK to work? But I'm not too sure.

The favicon is only used for the icon in the browser tab when the app is run locally.
![image](https://user-images.githubusercontent.com/35696678/129771279-c280dc61-899b-41be-a4ff-602f2b77f9ed.png)
Again that's something that was autogenerated (by Create React App this time) but it'd be simple enough to take that out if we don't want it.

2021-08-17 17:21 UTC, jthomperoo commented on CarbonComponents/README.md
> +. store/scripts/clean_and_run.sh
Oops! I managed to make a typo in my comment about the typo 🤦‍♂️

I think the script uses `-` instead of `_`, like `store/scripts/clean-and-run.sh`

2021-08-17 17:22 UTC, jthomperoo commented on CarbonComponents/app/static/qjslib/qappfw.min.js
> +this.qappfw=function(t){var e={};function r(n){if(e[n])return e[n].exports;var o=e[n]={i:n,l:!1,exports:{}};return t[n].call(o.exports,o,o.exports,r),o.l=!0,o.exports}return r.m=t,r.c=e,r.d=function(
Yes that makes sense, maybe remove the script and keep the favicon, the QJSLib is added by the qapp SDK, but it isn't needed here.

2021-08-23 09:40 UTC, erin-hughes commented on CarbonComponents/README.md
> +. store/scripts/clean_and_run.sh
Yes you're 100% right, will fix!

2021-08-23 10:06 UTC, jthomperoo approved these changes

2021-08-23 10:07 UTC, merged